Repository 2110503TACEDT66/cedt-se-project-mewing-komkom, pull requests merged in 2024-04, with the labels that each got.

#118 Fix prefetch data bug
  Frontend/src/app/booking/edit/[id]/page.tsx
Labels: bug

#116 Add maxSeat limitation to 5000
  Backend/controllers/workingspace.js
  Backend/models/WorkingSpace.js
  Frontend/src/components/admin/CreatCoWorkForm.tsx
Labels: bug

#119 feat: co-working status bar skeleton
  Frontend/src/components/Card.tsx
Labels: improvement

#123 Refetch quota after submitting
  Frontend/src/app/booking/edit/[id]/page.tsx
  Frontend/src/app/space/[id]/page.tsx
Labels: bug

#111 Jest test : Create and Edit Co-working space
  Backend/controllers/testCreate.js
  Backend/controllers/testEdit.js
  Backend/coverage/clover.xml
  Backend/coverage/coverage-final.json
  Backend/coverage/lcov-report/base.css
  Backend/coverage/lcov-report/block-navigation.js
  Backend/coverage/lcov-report/controllers/index.html
  Backend/coverage/lcov-report/controllers/testCreate.js.html
  Backend/coverage/lcov-report/controllers/testEdit.js.html
  Backend/coverage/lcov-report/favicon.png
  Backend/coverage/lcov-report/index.html
  Backend/coverage/lcov-report/models/WorkingSpace.js.html
  Backend/coverage/lcov-report/models/index.html
  Backend/coverage/lcov-report/models/test.Workingspace.js.html
  Backend/coverage/lcov-report/prettify.css
  Backend/coverage/lcov-report/prettify.js
  Backend/coverage/lcov-report/sort-arrow-sprite.png
  Backend/coverage/lcov-report/sorter.js
  Backend/coverage/lcov.info
  Backend/models/test.Workingspace.js
  Backend/package-lock.json
  Backend/package.json
  Backend/test/Create.test.js
  Backend/test/Edit.test.js
  Frontend/cypress.config.ts
  Frontend/src/components/admin/CreatCoWorkForm.tsx
Labels: wontfix
